###
POST http://localhost:3977/react/user/userModel HTTP/1.1
Content-Type: application/json
{
  "name": "Maria José",
  "lastname": "Jaramillo A",
  "email": "mariaj.jaramilloa@autonoma.edu.co",
  "password": "hola123",
  "active": "yes"
}
###
GET http://localhost:3977/react/user/userModel HTTP/1.1

###
GET http://localhost:3977/react/user/userModel HTTP/1.1

###
PUT http://localhost:3977/react/user/userModel HTTP/1.1
Content-Type: application/json
{
  "password": "AABFBBGB",
}
###
DELETE http://localhost:3977/react/user/userModel HTTP/1.1
